subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            project.android {
                namespace project.group.toString()

                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_17
                    targetCompatibility JavaVersion.VERSION_17
                }
            }
        }
    }
}
