# ── Flutter ────────────────────────────────────────────────────────────────────
-keep class io.flutter.** { *; }
-keep class io.flutter.embedding.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-dontwarn io.flutter.**

# GeneratedPluginRegistrant (generated by flutter pub get)
-keep class io.flutter.plugins.GeneratedPluginRegistrant { *; }

# ── Firebase ───────────────────────────────────────────────────────────────────
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
# P10-A: Keep type signatures for Firebase generics (StorageEngine, etc.) and
# preserve all annotations so Firebase Crashlytics stack traces are deobfuscated.
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn com.google.firebase.**
-dontwarn com.google.android.gms.**

# ── WebRTC (flutter_webrtc) ────────────────────────────────────────────────────
# P10-A: Both packages are required — org.webrtc is the Google WebRTC library;
# com.cloudwebrtc is the flutter_webrtc plugin wrapper that bridges Dart to JNI.
# R8 renames both sets of classes → ClassNotFoundException at peer-connection init.
-keep class org.webrtc.** { *; }
-keep class com.cloudwebrtc.** { *; }
-dontwarn org.webrtc.**
-dontwarn com.cloudwebrtc.**

# ── Native Kotlin classes (method channels, services, receivers) ───────────────
-keep class com.example.family_monitor.** { *; }

# ── Flutter background service ─────────────────────────────────────────────────
-keep class id.flutter.flutter_background_service.** { *; }
-dontwarn id.flutter.flutter_background_service.**

# ── Flutter foreground task ────────────────────────────────────────────────────
-keep class com.pravera.flutter_foreground_task.** { *; }
-dontwarn com.pravera.flutter_foreground_task.**

# ── Firebase Crashlytics ───────────────────────────────────────────────────────
# Keep source file names + line numbers so stack traces are readable in console.
-keepattributes SourceFile,LineNumberTable
-keep public class * extends java.lang.Exception
-keep class com.google.firebase.crashlytics.** { *; }

# ── AndroidX — TARGETED keeps only ────────────────────────────────────────────
# The old broad "-keep class androidx.** { *; }" blocked R8 from removing
# unused AndroidX code. Replace it with only the classes accessed by reflection.
-keep class androidx.core.app.CoreComponentFactory { *; }
-keep class androidx.lifecycle.DefaultLifecycleObserver { *; }
-keep class androidx.lifecycle.LifecycleObserver { *; }
-keep class androidx.localbroadcastmanager.content.LocalBroadcastManager { *; }
-dontwarn androidx.**

# ── WorkManager ────────────────────────────────────────────────────────────────
# Workers are instantiated via reflection — R8 must not remove their constructors.
-keep class * extends androidx.work.Worker { *; }
-keep class * extends androidx.work.CoroutineWorker { *; }
-keep class * extends androidx.work.ListenableWorker {
    public <init>(android.content.Context, androidx.work.WorkerParameters);
}
-keep class com.example.family_monitor.WatchdogWorker { *; }
-keep class com.example.family_monitor.WatchdogService { *; }
-keep class com.example.family_monitor.WatchdogScheduler { *; }

# ── Kotlin coroutines ──────────────────────────────────────────────────────────
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
-dontwarn kotlinx.coroutines.**

# ── Suppress common third-party warnings ──────────────────────────────────────
-dontwarn javax.annotation.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
